chore: update messages

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -39,24 +39,28 @@ check_bin_lib() {
   fi
 
   if [ "${LIBPRQLR_BUILD}" = "false" ] && [ -f "tools/lib-sums.tsv" ] && [ ! -f "${LIBPRQLR_PATH}" ] ; then
-    echo "Try to download pre-built binary..."
+    echo ""
+    echo "--------------- [ TRY TO DOWNLOAD PRE-BUILT BINARY ] ---------------"
     LIBPRQLR_PATH="tools/${LIBNAME}"
-    Rscript "tools/prep-lib.R" || echo "Failed to download pre-built binary..."
+    Rscript "tools/prep-lib.R" || echo "Failed to download pre-built binary."
+    echo "--------------------------------------------------------------------"
+    echo ""
   fi
 
   if [ "${LIBPRQLR_BUILD}" = "false" ] && [ -f "${LIBPRQLR_PATH}" ]; then
     echo ""
-    echo "------------------------- [LIBRARY FOUND] -------------------------"
+    echo "---------------------- [LIBRARY BINARY FOUND] ----------------------"
     echo "The library was found at <${LIBPRQLR_PATH}>. No need to build it."
-    echo "-------------------------------------------------------------------"
+    echo "--------------------------------------------------------------------"
     echo ""
     sed -e "s|@RUST_TARGET@||" src/Makevars.in >src/Makevars
     exit 0
   elif [ "${LIBPRQLR_BUILD}" = "false" ]; then
     echo ""
-    echo "----------------------- [LIBRARY NOT FOUND] -----------------------"
+    echo "-------------------- [LIBRARY BINARY NOT FOUND] --------------------"
     echo "The library was not found at <${LIBPRQLR_PATH}>."
-    echo "-------------------------------------------------------------------"
+    echo "Falling back to building from source."
+    echo "--------------------------------------------------------------------"
     echo ""
   fi
 }
