WIP feat(installation): download lib binaries

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,9 @@
 #!/usr/bin/env sh
 
+NOT_CRAN=${NOT_CRAN:-"false"}
+LIBPRQLR_BUILD=${LIBPRQLR_BUILD:-""}
+LIBNAME="libprqlr.a"
+
 export PATH="$PATH:$HOME/.cargo/bin"
 
 check_cargo() {
@@ -18,6 +22,29 @@ check_cargo() {
   fi
 }
 
+check_bin_lib() {
+  if [ "${NOT_CRAN}" = "true" ] && [ -z "${LIBPRQLR_BUILD}"  ]; then
+    LIBPRQLR_BUILD="false"
+  fi
+
+  if [ "${LIBPRQLR_BUILD}" = "false" ] && [ -f "tools/lib-sums.tsv" ] && [ ! -f "tools/${LIBNAME}" ] ; then
+    echo "Try to download pre-built binary..."
+    Rscript "tools/prep-lib.R" || echo "Failed to download pre-built binary..."
+  fi
+
+  if [ "${LIBPRQLR_BUILD}" = "false" ] && [ -f "tools/${LIBNAME}" ]; then
+    echo "----------------------- [LIBRARY FOUND]---------------------------"
+    echo "The library was found in the tools directory. No need to build it."
+    echo "-------------------------------------------------------------------"
+    echo ""
+    sed -e "s|@RUST_TARGET@||" src/Makevars.in >src/Makevars
+    exit 0
+  fi
+}
+
+check_bin_lib
 check_cargo
+
+sed -e "s|@RUST_TARGET@|$(rustc -vV | grep host | cut -d' ' -f2)|" src/Makevars.in >src/Makevars
 
 exit 0
